# Basic ESPHome Configuration for the S31 Power Outlet

esphome:
  name: living-room-bar-outlet
  friendly_name: Living Room Bar Outlet

esp8266:
  board: esp01_1m

uart:
  rx_pin: RX
  baud_rate: 4800
  parity: EVEN

# Enable logging
logger:
  baud_rate: 0

# Enable Home Assistant API
api:

ota:
- platform: esphome

#WiFi + Web Server Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  port: 80
  include_internal: true

#Relay Configuration
switch:
  - platform: gpio
    name: "Relay"
    icon: "mdi:power-socket-us"
    pin: GPIO12
    id: relay
    restore_mode: ALWAYS_ON

#Physical Power Button Configuratoin
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Physical Power Button"
    on_press:
      - switch.toggle: relay

sensor:
  - platform: wifi_signal
    name: "WiFi Signal"
    update_interval: 60s
  - platform: cse7766
    current:
      name: "Current"
      accuracy_decimals: 2
    voltage:
      name: "Voltage"
      accuracy_decimals: 1
    power:
      name: "Power"
      accuracy_decimals: 2
      id: my_power

time:
  - platform: sntp
    id: my_time

#Enable the device LED
status_led:
  pin: GPIO13